index:
  path: /
  controller: App\Controller\HomeController::index

listMannschaften:
  path: /mannschaften
  methods: GET
  controller: App\Controller\TeamController::list

addMannschaft:
  path: /mannschaft
  methods: POST
  controller: App\Controller\TeamController::add