index:
  path: /
  controller: App\Controller\HomeController::index

listMannschaften:
  path: /mannschaften
  methods: GET
  controller: App\Controller\TeamController::list

createMannschaft:
  path: /mannschaft
  methods: POST
  controller: App\Controller\TeamController::create

readMannschaft:
  path: /mannschaft/{id}
  methods: GET
  controller: App\Controller\TeamController::read

updateMannschaft:
  path: /mannschaft/{id}
  methods: PUT
  controller: App\Controller\TeamController::update

listGame:
  path: /games
  methods: GET
  controller: App\Controller\GameController::list

createGame:
  path: /games
  methods: POST
  controller: App\Controller\GameController::create

readGame:
  path: /games
  methods: READ
  controller: App\Controller\GameController::read

updateGame:
  path: /games/{id}
  methods: PUT
  controller: App\Controller\GameController::update

deleteGame:
  path: /games
  methods: DELETE
  controller: App\Controller\GameController::delete